import { MutableRefObject } from 'react'

import { getCronStringFromValues, setValuesFromCronString } from './converter'
import { AllowEmpty, PeriodType, Shortcuts } from './types'

describe('converter setValuesFromCronString function test suite', () => {
  const testCases: {
    title: string
    cronString: string | number // number to test wrong value type
    allowEmpty: AllowEmpty
    firstRender: boolean
    shortcuts: Shortcuts
    error: boolean
    expectedNbCallsSetMinutes: number
    expectedParamSetMinutes: number[] | undefined
    expectedNbCallsSetHours: number
    expectedParamSetHours: number[] | undefined
    expectedNbCallsSetMonthDays: number
    expectedParamSetMonthDays: number[] | undefined
    expectedNbCallsSetMonths: number
    expectedParamSetMonths: number[] | undefined
    expectedNbCallsSetWeekDays: number
    expectedParamSetWeekDays: number[] | undefined
    expectedNbCallsSetPeriod: number
    expectedParamSetPeriod: PeriodType | undefined
  }[] = [
    {
      title: 'a valid cron with unique value for single unit',
      cronString: '40 * * * *',
      allowEmpty: 'for-default-value',
      firstRender: false,
      shortcuts: false,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [40],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'hour',
    },
    {
      title: 'a valid cron with multiple values for single unit',
      cronString: '2,5,8,40 * * * *',
      allowEmpty: 'for-default-value',
      firstRender: false,
      shortcuts: false,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [2, 5, 8, 40],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'hour',
    },
    {
      title: 'a valid cron with single value for multiple units',
      cronString: '3 2 * * *',
      allowEmpty: 'for-default-value',
      firstRender: false,
      shortcuts: false,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [3],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [2],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'day',
    },
    {
      title:
        'that an empty string is allowed on first render with allowEmpty always',
      cronString: '',
      allowEmpty: 'always',
      firstRender: true,
      shortcuts: false,
      error: false,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title:
        'that an empty string is allowed on second render with allowEmpty always',
      cronString: '',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: false,
      error: false,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title:
        'that en empty string is allowed on first render with allowEmpty for-default-value',
      cronString: '',
      allowEmpty: 'for-default-value',
      firstRender: true,
      shortcuts: false,
      error: false,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title:
        'that an empty string is not allowed on second render with allowEmpty for-default-value',
      cronString: '',
      allowEmpty: 'for-default-value',
      firstRender: false,
      shortcuts: false,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title:
        'that an empty string is not allowed on first render with allowEmpty never',
      cronString: '',
      allowEmpty: 'never',
      firstRender: true,
      shortcuts: false,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title:
        'that an empty string is not allowed on second render with allowEmpty never',
      cronString: '',
      allowEmpty: 'never',
      firstRender: false,
      shortcuts: false,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'a wrong value string throw an error',
      cronString: 'wrong value',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: false,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'a wrong value number throw an error',
      cronString: 200,
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: false,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'all units values filled set year period',
      cronString: '1 2 3 4 5',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: false,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [1],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [2],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [3],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [4],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [5],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'year',
    },
    {
      title: 'that a range is allowed when valid',
      cronString: '1 2 3-9/3 4 5',
      allowEmpty: 'for-default-value',
      firstRender: false,
      shortcuts: false,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [1],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [2],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [3, 6, 9],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [4],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [5],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'year',
    },
    {
      title: 'that reboot shortcut is allowed when shortcuts is true',
      cronString: '@reboot',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: false,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'reboot',
    },
    {
      title: 'that reboot shortcut is not allowed when shortcuts is false',
      cronString: '@reboot',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: false,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'that monthly shortcut is allowed when shortcuts is true',
      cronString: '@monthly',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [0],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [0],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [1],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'month',
    },
    {
      title:
        'that monthly shortcut is not allowed when shortcuts only accept reboot',
      cronString: '@monthly',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: ['@reboot'],
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'that monthly shortcut is allowed when shortcuts accept @monthly',
      cronString: '@monthly',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: ['@monthly'],
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [0],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [0],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [1],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'month',
    },
    {
      title: 'that a wrong shortcut is not allowed',
      cronString: '@wrongShortcut',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: ['@wrongShortcut'] as unknown as Shortcuts,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'all unit filled with every set minute period',
      cronString: '* * * * *',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'minute',
    },
    {
      title: 'only week day value set week period',
      cronString: '* * * * 1',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [1],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'week',
    },
    {
      title: '7 for sunday converted to 0',
      cronString: '* * * * 7',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [0],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'week',
    },
    {
      title: 'humanized value converted to number',
      cronString: '* * * MAY SUN',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [5],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [0],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'year',
    },
    {
      title: 'wrong range with double "/" throw an error',
      cronString: '2/2/2 * * * *',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'full week days definition set every',
      cronString: '* * * * 0,1,2,3,4,5,6',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'minute',
    },
    {
      title: 'range with every two week days is allowed',
      cronString: '* * * * */2',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: false,
      expectedNbCallsSetMinutes: 1,
      expectedParamSetMinutes: [],
      expectedNbCallsSetHours: 1,
      expectedParamSetHours: [],
      expectedNbCallsSetMonthDays: 1,
      expectedParamSetMonthDays: [],
      expectedNbCallsSetMonths: 1,
      expectedParamSetMonths: [],
      expectedNbCallsSetWeekDays: 1,
      expectedParamSetWeekDays: [0, 2, 4, 6],
      expectedNbCallsSetPeriod: 1,
      expectedParamSetPeriod: 'week',
    },
    {
      title: 'an out of range value too low throw an error',
      cronString: '* * * * -1',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'an out of range value too big throw an error',
      cronString: '* * * * 200',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title:
        'that a range first value greater than second value throw an error',
      cronString: '* * * * 5-2',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'wrong range with more than one separator throw an error',
      cronString: '* * * * 5-2-2',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'wrong range first part throw an error',
      cronString: '* * * * error/2',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
    {
      title: 'wrong range second part throw an error',
      cronString: '* * * * 2/error',
      allowEmpty: 'always',
      firstRender: false,
      shortcuts: true,
      error: true,
      expectedNbCallsSetMinutes: 0,
      expectedParamSetMinutes: undefined,
      expectedNbCallsSetHours: 0,
      expectedParamSetHours: undefined,
      expectedNbCallsSetMonthDays: 0,
      expectedParamSetMonthDays: undefined,
      expectedNbCallsSetMonths: 0,
      expectedParamSetMonths: undefined,
      expectedNbCallsSetWeekDays: 0,
      expectedParamSetWeekDays: undefined,
      expectedNbCallsSetPeriod: 0,
      expectedParamSetPeriod: undefined,
    },
  ]

  testCases.forEach(
    ({
      title,
      cronString,
      allowEmpty,
      firstRender,
      shortcuts,
      error,
      expectedParamSetMinutes,
      expectedParamSetHours,
      expectedParamSetMonthDays,
      expectedParamSetMonths,
      expectedParamSetWeekDays,
      expectedParamSetPeriod,
      expectedNbCallsSetHours,
      expectedNbCallsSetMinutes,
      expectedNbCallsSetMonthDays,
      expectedNbCallsSetMonths,
      expectedNbCallsSetPeriod,
      expectedNbCallsSetWeekDays,
    }) => {
      it(`should check ${title}`, () => {
        const setInternalError = jest.fn()
        const onError = jest.fn()
        const internalValueRef: MutableRefObject<string> = {
          current: '',
        }
        const locale = {}
        const setMinutes = jest.fn()
        const setHours = jest.fn()
        const setMonthDays = jest.fn()
        const setMonths = jest.fn()
        const setWeekDays = jest.fn()
        const setPeriod = jest.fn()

        setValuesFromCronString(
          cronString as string,
          setInternalError,
          onError,
          allowEmpty,
          internalValueRef,
          firstRender,
          locale,
          shortcuts,
          setMinutes,
          setHours,
          setMonthDays,
          setMonths,
          setWeekDays,
          setPeriod
        )

        //
        // Error check

        expect(onError).toHaveBeenCalledTimes(error ? 2 : 1)
        expect(onError).toHaveBeenCalledWith(
          error
            ? {
                type: 'invalid_cron',
                description: 'Invalid cron expression',
              }
            : undefined
        )

        expect(setInternalError).toHaveBeenCalledTimes(error ? 2 : 1)
        expect(setInternalError).toHaveBeenCalledWith(error)

        //
        // Values setter check

        expect(setMinutes).toHaveBeenCalledTimes(expectedNbCallsSetMinutes)
        if (expectedParamSetMinutes) {
          expect(setMinutes).toHaveBeenCalledWith(expectedParamSetMinutes)
        }

        expect(setHours).toHaveBeenCalledTimes(expectedNbCallsSetHours)
        if (expectedParamSetHours) {
          expect(setHours).toHaveBeenCalledWith(expectedParamSetHours)
        }

        expect(setMonthDays).toHaveBeenCalledTimes(expectedNbCallsSetMonthDays)
        if (expectedParamSetMonthDays) {
          expect(setMonthDays).toHaveBeenCalledWith(expectedParamSetMonthDays)
        }

        expect(setMonths).toHaveBeenCalledTimes(expectedNbCallsSetMonths)
        if (expectedParamSetMonths) {
          expect(setMonths).toHaveBeenCalledWith(expectedParamSetMonths)
        }

        expect(setWeekDays).toHaveBeenCalledTimes(expectedNbCallsSetWeekDays)
        if (expectedParamSetWeekDays) {
          expect(setWeekDays).toHaveBeenCalledWith(expectedParamSetWeekDays)
        }

        expect(setPeriod).toHaveBeenCalledTimes(expectedNbCallsSetPeriod)
        if (expectedParamSetPeriod) {
          expect(setPeriod).toHaveBeenCalledWith(expectedParamSetPeriod)
        }
      })
    }
  )
})

describe('converter getCronStringFromValues function test suite', () => {
  const testCases: {
    title: string
    period: PeriodType
    months: number[] | undefined
    monthDays: number[] | undefined
    weekDays: number[] | undefined
    hours: number[] | undefined
    minutes: number[] | undefined
    humanizeValue: boolean
    expectedValue: string | undefined
    error?: string
  }[] = [
    {
      title: 'valid cron values with unique values for all units',
      period: 'year',
      minutes: [1],
      hours: [2],
      monthDays: [3],
      months: [4],
      weekDays: [5],
      humanizeValue: false,
      expectedValue: '1 2 3 4 5',
    },
    {
      title: 'valid cron values with unique values for multiple units',
      period: 'day',
      minutes: [1],
      hours: [2],
      monthDays: [3],
      months: [4],
      weekDays: [5],
      humanizeValue: false,
      expectedValue: '1 2 * * *',
    },
    {
      title: 'valid cron values with a unique value for a single unit',
      period: 'day',
      minutes: [1],
      hours: [],
      monthDays: [],
      months: [],
      weekDays: [],
      humanizeValue: false,
      expectedValue: '1 * * * *',
    },
    {
      title: 'valid cron values with multiple values for multiple units',
      period: 'year',
      minutes: [1],
      hours: [2],
      monthDays: [3],
      months: [7, 3, 10],
      weekDays: [5],
      humanizeValue: false,
      expectedValue: '1 2 3 3,7,10 5',
    },
    {
      title: 'valid cron values with humanized values',
      period: 'year',
      minutes: [1],
      hours: [2],
      monthDays: [3],
      months: [7, 3, 10],
      weekDays: [5],
      humanizeValue: true,
      expectedValue: '1 2 3 MAR,JUL,OCT FRI',
    },
    {
      title: 'valid cron values with reboot shortcut',
      period: 'reboot',
      minutes: [],
      hours: [],
      monthDays: [],
      months: [],
      weekDays: [],
      humanizeValue: false,
      expectedValue: '@reboot',
    },
    {
      title: 'valid cron values with period that remove unnecessary values',
      period: 'month',
      minutes: undefined,
      hours: undefined,
      monthDays: [3],
      months: [7, 3, 10],
      weekDays: [5],
      humanizeValue: false,
      expectedValue: '* * 3 * 5',
    },
    {
      title: 'valid cron values with every',
      period: 'year',
      minutes: undefined,
      hours: undefined,
      monthDays: undefined,
      months: undefined,
      weekDays: undefined,
      humanizeValue: false,
      expectedValue: '* * * * *',
    },
    {
      title: 'valid cron values with every 2 week days',
      period: 'year',
      minutes: [0],
      hours: [1],
      monthDays: [1],
      months: [5],
      weekDays: [0, 2, 4, 6],
      humanizeValue: false,
      expectedValue: '0 1 1 5 */2',
    },
    {
      title: 'valid cron values with step range definition',
      period: 'year',
      minutes: [0],
      hours: [1],
      monthDays: [3, 6, 9],
      months: [5],
      weekDays: [0, 2, 4, 6],
      humanizeValue: false,
      expectedValue: '0 1 3-9/3 5 */2',
    },
    {
      title: 'valid cron values with simple range definition',
      period: 'year',
      minutes: [0],
      hours: [1],
      monthDays: [3, 4, 5],
      months: [5],
      weekDays: [0, 2, 4, 6],
      humanizeValue: false,
      expectedValue: '0 1 3-5 5 */2',
    },
    {
      title: 'invalid cron values with a too big value',
      period: 'year',
      minutes: [0],
      hours: [1],
      monthDays: [3, 4, 500],
      months: [5],
      weekDays: [0, 2, 4, 6],
      humanizeValue: false,
      expectedValue: undefined,
      error: 'Value "500" out of range for month-days',
    },
    {
      title: 'invalid cron values with a too low value',
      period: 'year',
      minutes: [0],
      hours: [1],
      monthDays: [3, 4, -1],
      months: [5],
      weekDays: [0, 2, 4, 6],
      humanizeValue: false,
      expectedValue: undefined,
      error: 'Value "-1" out of range for month-days',
    },
  ]

  testCases.forEach(
    ({
      title,
      period,
      hours,
      humanizeValue,
      minutes,
      monthDays,
      months,
      weekDays,
      expectedValue,
      error,
    }) => {
      it(`should check ${title}`, () => {
        try {
          expect(
            getCronStringFromValues(
              period,
              months as number[] | undefined,
              monthDays,
              weekDays,
              hours,
              minutes,
              humanizeValue
            )
          ).toEqual(expectedValue)
        } catch (e) {
          expect(e.message).toEqual(error)
        }
      })
    }
  )
})
