name: Storybook

on:
  push:
    branches:
      - master

jobs:
  storybook:
    runs-on: ubuntu-latest
    name: Build Storybook
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: corepack enable
      - name: Install dependencies
        run: yarn --immutable
      - name: Run build-storybook
        run: yarn build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
          FORCE: true
