name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: npm ci --legacy-peer-deps
      - name: Run tests and collect coverage
        run: npm run test:ci
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
